#!/bin/bash

regex='^[]0-9a-zA-Z,!^`@{}=().;/~_|[-]+$'

for file in uploads/*; do

  ba=-n "${b//[[:space:]]/}"
  echo ba
   b=$(basename "$file")
   if [[ "$b" =~ "$regex" ]]
   then
     ls uploads
     php talktomeS3.php "$b"
     echo "$b"
     rm -f "$file"

   fi

done
